const stroji = [
  {vrsta:"Bager",proizvajalec:"LIUGONG",tip:"926FN",inventar:"579/N"},
  {vrsta:"Bager",proizvajalec:"HYUNDAI",tip:"HW140",inventar:"1833"},
  {vrsta:"Bager",proizvajalec:"HYUNDAI",tip:"HW140",inventar:"1834"},
  {vrsta:"Bager",proizvajalec:"HYUNDAI",tip:"HW140",inventar:"1835"},
  {vrsta:"Bager",proizvajalec:"HYUNDAI",tip:"HW180",inventar:"1928"},
  {vrsta:"Bager",proizvajalec:"HYUNDAI",tip:"HV 100",inventar:"2012"},
  {vrsta:"Bager",proizvajalec:"HYUNDAI",tip:"80CR - 9A",inventar:"2010"},
  {vrsta:"Bager",proizvajalec:"HYUNDAI",tip:"80CR - 9A",inventar:"2011"},
  {vrsta:"Bager",proizvajalec:"JCB",tip:"801,7",inventar:"1210"},
  {vrsta:"Bager",proizvajalec:"CAT",tip:"308CCR",inventar:"1393"},
  {vrsta:"Bager",proizvajalec:"JCB",tip:"8050",inventar:"1805"},
  {vrsta:"Bager",proizvajalec:"JCB",tip:"8050",inventar:"1806"},
  {vrsta:"Bager",proizvajalec:"KOMATSU",tip:"230 - NHD",inventar:"1822"},
  {vrsta:"Bager",proizvajalec:"KOMATSU",tip:"PC 55 MR",inventar:"1823"},
  {vrsta:"Bager",proizvajalec:"KOMATSU",tip:"PC 78 MR",inventar:"1824"},
  {vrsta:"Bager",proizvajalec:"KOMATSU",tip:"PC 210",inventar:"1850"},
  {vrsta:"Bager",proizvajalec:"LIUGONG",tip:"909 ECR",inventar:"1941"},
  {vrsta:"Bager",proizvajalec:"HYUNDAI",tip:"ROBEX 32Z - 9A",inventar:"2030"},
  {vrsta:"Bager",proizvajalec:"KOBELKO",tip:"SK 350 NLC",inventar:"424/N"},
  {vrsta:"Bager",proizvajalec:"TAKEUCHI",tip:"TB 215",inventar:"580/N"},
  {vrsta:"Bager",proizvajalec:"KOBELKO",tip:"SK 180",inventar:"592/N"},
  {vrsta:"Bager",proizvajalec:"HYUNDAI",tip:"ROBEX 25Z - 9A",inventar:"662/N"},
  {vrsta:"Bager",proizvajalec:"VOLVO",tip:"EC 300ENL",inventar:"1725"},
  {vrsta:"Gredar",proizvajalec:"O&K",tip:"F 106A",inventar:"1040"},
  {vrsta:"Gredar",proizvajalec:"CATERPILAR",tip:"12G",inventar:"1607"},
  {vrsta:"Gredar",proizvajalec:"CHAMPION",tip:"730A",inventar:"1000"},
  {vrsta:"Rovokopač",proizvajalec:"JCB",tip:"4CX",inventar:"1212"},
  {vrsta:"Rovokopač",proizvajalec:"JCB",tip:"4CX",inventar:"1810"},
  {vrsta:"Rovokopač",proizvajalec:"JCB",tip:"4CX",inventar:"1811"},
  {vrsta:"Rovokopač",proizvajalec:"JCB",tip:"4CX",inventar:"1859"},
  {vrsta:"Rovokopač",proizvajalec:"JCB",tip:"4CX",inventar:"1983"},
  {vrsta:"Buldožer",proizvajalec:"CAT",tip:"D8 T",inventar:"1804"},
  {vrsta:"Nakladač",proizvajalec:"VOLVO",tip:"4600",inventar:"889"},
  {vrsta:"Nakladač",proizvajalec:"VOLVO",tip:"L150E",inventar:"1295"},
  {vrsta:"Nakladač",proizvajalec:"VOLVO",tip:"L180H",inventar:"1665"},
  {vrsta:"Nakladač",proizvajalec:"NEW HOLAND",tip:"170 B",inventar:"1484"},
  {vrsta:"Nakladač",proizvajalec:"LIUGONG",tip:"877H",inventar:"1851"},
  {vrsta:"Nakladač",proizvajalec:"LIUGONG",tip:"877H",inventar:"1940"},
  {vrsta:"Nakladač",proizvajalec:"LIUGONG",tip:"877H",inventar:"1999"},
  {vrsta:"Nakladač",proizvajalec:"HYUNDAI",tip:"HL 975 A",inventar:"2002"},
  {vrsta:"Nakladač",proizvajalec:"HIDROMEK",tip:"640",inventar:"826/N"},
  {vrsta:"Nakladač",proizvajalec:"BOB CAT",tip:"S175",inventar:"1860"},
  {vrsta:"Nakladač",proizvajalec:"BOB CAT",tip:"S175",inventar:"1618"},
  {vrsta:"Demper",proizvajalec:"NCS",tip:"W6",inventar:"1681"},
  {vrsta:"Demper",proizvajalec:"NCS",tip:"W6",inventar:"1686"},
  {vrsta:"Demper",proizvajalec:"NCS",tip:"W3",inventar:"1687"},
  {vrsta:"Demper",proizvajalec:"NEUSON",tip:"6001",inventar:"1695"},
  {vrsta:"Demper",proizvajalec:"NEUSON",tip:"6001",inventar:"1696"},
  {vrsta:"Demper",proizvajalec:"BENFORD",tip:"6T",inventar:"1740"},
  {vrsta:"Demper",proizvajalec:"NEUSON",tip:"6001",inventar:"1827"},
  {vrsta:"Demper",proizvajalec:"NCS",tip:"6 SW 5560",inventar:"1997"},
  {vrsta:"Demper",proizvajalec:"TEREX",tip:"TA 3,5",inventar:"2038"},
  {vrsta:"Demper",proizvajalec:"NCS",tip:"6 SW 5560",inventar:"2044"},
  {vrsta:"Demper",proizvajalec:"METALAC",tip:"TA 3,5 SH",inventar:"2046"},
  {vrsta:"Kompresor",proizvajalec:"ATLAS COPKO",tip:"26/AF",inventar:"1169"},
  {vrsta:"Kompresor",proizvajalec:"ATLAS COPKO",tip:"Xas 88-10",inventar:"1411"},
  {vrsta:"Kompresor",proizvajalec:"ATLAS COPKO",tip:"Xas 57",inventar:"2007"},
  {vrsta:"Traktor",proizvajalec:"STAYER",tip:"83 TK",inventar:"935"},
  {vrsta:"Traktor",proizvajalec:"VALTRA",tip:"134 D",inventar:"1807"},
  {vrsta:"Traktor",proizvajalec:"VALTRA",tip:"235 D",inventar:"1976"},
  {vrsta:"Traktor",proizvajalec:"GOLDONI",tip:"STAR 100",inventar:"402/N"},
  {vrsta:"Rezkar za asfalt",proizvajalec:"WIRTGEN",tip:"W2000",inventar:"1483"},
  {vrsta:"Rezkar za asfalt",proizvajalec:"WIRTGEN",tip:"W100",inventar:"1659"},
  {vrsta:"Rezkar za asfalt",proizvajalec:"WIRTGEN",tip:"W50",inventar:"18670"},
  {vrsta:"Reciklator",proizvajalec:"WIRTGEN",tip:"2500",inventar:"1486"},
  {vrsta:"Svetlobni stolp",proizvajalec:"LUXTOWER",tip:"M11-E",inventar:"2575"},
  {vrsta:"Svetlobni stolp",proizvajalec:"LUXTOWER",tip:"M11-E",inventar:"2576"},
  {vrsta:"Svetlobni stolp",proizvajalec:"GENERAC",tip:"-",inventar:"2585"},
  {vrsta:"Snežni rezkar",proizvajalec:"ROLBA",tip:"400",inventar:"797"},
  {vrsta:"Finišer",proizvajalec:"VOGELE",tip:"1803 - 3i",inventar:"1674"},
  {vrsta:"Valjar",proizvajalec:"HAMM",tip:"HD 12 - gumi",inventar:"1454"},
  {vrsta:"Valjar",proizvajalec:"HAMM",tip:"HD 14 - VT - gumi",inventar:"1668"},
  {vrsta:"Valjar",proizvajalec:"BOMAG",tip:"BW 120 - gumi",inventar:"2049"},
  {vrsta:"Valjar",proizvajalec:"HAMM",tip:"HD + 80 VT - gumi",inventar:"2053"},
  {vrsta:"Valjar",proizvajalec:"HAMM",tip:"HD 9 VT - gumi",inventar:"2006"}
];