const strojniki = {
  "1":"ABDIĆ SAID","2":"ANDRAŠEC LEON","3":"ARSENIĆ DAVID","4":"BOBNAR JOŽEF",
  "5":"BOŽIĆ DALIBOR","6":"BUNIĆ SABAHUDIN","7":"BURZIČ ANES","8":"ČEMAŽAR ALJAŽ",
  "9":"DRAKSLER SIMON","10":"DURDŽIĆ ALMIN","11":"ĐOKIĆ BORIS","12":"DŽUKANOVIĆ ANTON",
  "13":"ERIĆ GORAN","14":"ERIĆ ZORAN","15":"GROBIN DAMJAN","16":"GVERO ZORAN",
  "17":"HADŽIĆ ARIF","18":"HADŽIĆ NEVZAD","19":"HALILOVIĆ ALMIR","20":"IBRIČIĆ HIMZO",
  "21":"IBRIČIĆ ŠEĆER","22":"JENKO FRANCI","23":"KALAN MARK","24":"KAPIĆ AMIR",
  "25":"KAVAR JANEZ","26":"KERKEZ SABAHET","27":"KERN ANŽE","28":"KERT UROŠ",
  "29":"KLJUČIĆ ANEL","30":"KNEŽEVIĆ DRAGAN","31":"KOKIĆ IZET","32":"KOZJEK ANŽE",
  "33":"KREK LENART","34":"LAZIKIĆ ZORAN","35":"LAZIĆ SINIŠA","36":"MALEŠEVIĆ VELEMIR",
  "37":"MALEŠEVIĆ MILANKO","38":"MEGLIČ SIMEON","39":"MIDŽAN ERMIN","40":"MITROVIĆ GORAN",
  "41":"MOLJ BOŠTJAN","42":"NIKOLIČ BRANKO","43":"NOVAKOVIĆ VUJADIN","44":"NUHANOVIĆ HASAN",
  "45":"PECIĆ NEMANJA","46":"PEKEZ SLAVIŠA","47":"PERNUŠ ANDREJ","48":"POVŠNAR JURIJ",
  "49":"PROSEN KRISTIJAN","50":"REBOL MILAN","51":"RADIČ LUKA","52":"SAJOVIC KLEMEN",
  "53":"SMAJLOVIĆ ASMIR","54":"SOFRIĆ RADKO","55":"STUBIČAR IZIDOR","56":"ŠAHINOVIĆ ASMIR",
  "57":"ŠPEGLIČ MATIJA","58":"TSEKOV MIHAYLO","59":"TONEJC PETER","60":"VELAGIĆ ANES",
  "61":"VELIĆ HAJRUDIN","62":"VIDOVIĆ MIODRAG","63":"VUKALIĆ HUSEJIN","64":"ZADNIKAR ANDREJ",
  "65":"ZAPLOTNIK URBAN","66":"ZUPAN GREGA","67":"ŽVAN PRIMOŽ"
};